### ISSUE TITLE
WBC and Platelets labels are missing

### ISSUE THREAD

**Issue by rezacsedu** [Shenggan/BCCD_Dataset#1]
Hi @Shenggan,

I was exploring the dataset and realized that there are no labels in the Annotation files apart from RBC. But, In the readme file, the following is mentioned:

We have three kinds of labels: 
    RBC (Red Blood Cell)
    WBC (White Blood Cell)
    Platelets (血小板)

**Comment by Lynkzhang** [comment]
I guess you can have a look at other xml files . Not all samples have all three kind of cells.

**Comment by Lynkzhang** [comment]
Since most of the labels would be RBC, pls read the files carefully, or use ctrl+F

**Comment by rezacsedu** [comment]
@Lynkzhang, Ah, OK, found them. I was checking the files randomly. Sorry for the inconvenience.
