### ISSUE TITLE
What level of magnification was used for taking the pictures?

### ISSUE THREAD

**Issue by faaip** [Shenggan/BCCD_Dataset#7]
Hi!

Thanks for this dataset. Do you know what magnification levels were used for taking these pictures?

Thanks

**Comment by Shenggan** [comment]
Original data and annotations are from [cosmicad](https://github.com/cosmicad/dataset) and [akshaylamba](https://github.com/akshaylamba/all_CELL_data), so I don't know the magnification levels exactly. But I estimate the magnification is about 300x to 500x.
